version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/myapp
    overwrite: yes

permissions:
  - object: /home/ubuntu/myapp
    pattern: "**"
    owner: root
    group: root

hooks:
  ApplicationStart:
    - location: scripts/start_docker_container.sh
      timeout: 120
      runas: root