name: Java CI with Gradle

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Checkout submodule
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SUB_MODULE }}
          submodules: true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Copy submodule
        run: ./gradlew copySubmodule

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Build Docker image
        run: docker build --tag yerimsw/myapp:latest .

      - name: Log in to DockerHub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to DockerHub
        run: docker push yerimsw/myapp:latest
